var searchData=
[
  ['sanitycheck',['SanityCheck',['../class_aero_gear_1_1_mobile_1_1_core_1_1_utils_1_1_sanity_check.html',1,'AeroGear::Mobile::Core::Utils']]],
  ['sanitycheck_2ecs',['SanityCheck.cs',['../_sanity_check_8cs.html',1,'']]],
  ['save',['Save',['../class_aero_gear_1_1_mobile_1_1_core_1_1_storage_1_1_secure_key_value_store.html#a9259e9dbe30625a450e3f773fd47a088',1,'AeroGear::Mobile::Core::Storage::SecureKeyValueStore']]],
  ['scopes',['Scopes',['../class_aero_gear_1_1_mobile_1_1_auth_1_1_config_1_1_authentication_config.html#ae2b281720a2d7e332bfb0b8d781c7a7d',1,'AeroGear.Mobile.Auth.Config.AuthenticationConfig.Scopes()'],['../class_aero_gear_1_1_mobile_1_1_auth_1_1_config_1_1_authentication_config_1_1_authentication_config_builder.html#a49c2b96ef4c66bd61e76f67b9f0358b5',1,'AeroGear.Mobile.Auth.Config.AuthenticationConfig.AuthenticationConfigBuilder.Scopes()']]],
  ['securekeyvaluestore',['SecureKeyValueStore',['../class_aero_gear_1_1_mobile_1_1_core_1_1_storage_1_1_secure_key_value_store.html',1,'AeroGear.Mobile.Core.Storage.SecureKeyValueStore'],['../class_aero_gear_1_1_mobile_1_1_core_1_1_storage_1_1_secure_key_value_store.html#a86e9f02847770c9bbf29504200208e32',1,'AeroGear.Mobile.Core.Storage.SecureKeyValueStore.SecureKeyValueStore()']]],
  ['securekeyvaluestore_2ecs',['SecureKeyValueStore.cs',['../_secure_key_value_store_8cs.html',1,'']]],
  ['sendappanddevicemetrics',['SendAppAndDeviceMetrics',['../class_aero_gear_1_1_mobile_1_1_core_1_1_metrics_1_1_metrics_service.html#aadde32250de40b9bc5e8b9798e13ac4a',1,'AeroGear::Mobile::Core::Metrics::MetricsService']]],
  ['serializedcredential',['SerializedCredential',['../interface_aero_gear_1_1_mobile_1_1_auth_1_1_credentials_1_1_i_credential.html#ad3f98410cf0e56f1b3c5925a75faf8c8',1,'AeroGear::Mobile::Auth::Credentials::ICredential']]],
  ['serviceconfiguration',['ServiceConfiguration',['../class_aero_gear_1_1_mobile_1_1_core_1_1_configuration_1_1_service_configuration.html',1,'AeroGear::Mobile::Core::Configuration']]],
  ['serviceconfiguration_2ecs',['ServiceConfiguration.cs',['../_service_configuration_8cs.html',1,'']]],
  ['serviceconfigurationbuilder',['ServiceConfigurationBuilder',['../class_aero_gear_1_1_mobile_1_1_core_1_1_configuration_1_1_service_configuration_1_1_service_configuration_builder.html',1,'AeroGear::Mobile::Core::Configuration::ServiceConfiguration']]],
  ['servicefinder_2ecs',['ServiceFinder.cs',['../_service_finder_8cs.html',1,'']]],
  ['serviceinstancecache',['ServiceInstanceCache',['../class_aero_gear_1_1_mobile_1_1_core_1_1_service_instance_cache.html',1,'AeroGear::Mobile::Core']]],
  ['servicemoduleinstancenotfoundexception',['ServiceModuleInstanceNotFoundException',['../class_aero_gear_1_1_mobile_1_1_core_1_1_exception_1_1_service_module_instance_not_found_exception.html',1,'AeroGear.Mobile.Core.Exception.ServiceModuleInstanceNotFoundException'],['../class_aero_gear_1_1_mobile_1_1_core_1_1_exception_1_1_service_module_instance_not_found_exception.html#a78be4f838462dec0a50834c8f4edb861',1,'AeroGear.Mobile.Core.Exception.ServiceModuleInstanceNotFoundException.ServiceModuleInstanceNotFoundException(String message)'],['../class_aero_gear_1_1_mobile_1_1_core_1_1_exception_1_1_service_module_instance_not_found_exception.html#a8a75243f4aa51c44d682e1e3c99e9584',1,'AeroGear.Mobile.Core.Exception.ServiceModuleInstanceNotFoundException.ServiceModuleInstanceNotFoundException(String message, System.Exception exception)']]],
  ['servicemoduleinstancenotfoundexception_2ecs',['ServiceModuleInstanceNotFoundException.cs',['../_service_module_instance_not_found_exception_8cs.html',1,'']]],
  ['statuscode',['StatusCode',['../interface_aero_gear_1_1_mobile_1_1_core_1_1_http_1_1_i_http_response.html#a080b437c9a83f800038f78d384dce7ca',1,'AeroGear::Mobile::Core::Http::IHttpResponse']]],
  ['store',['Store',['../class_aero_gear_1_1_mobile_1_1_auth_1_1_credentials_1_1_credential_manager.html#a4c720c5ce7cd6312decda56469ddeeca',1,'AeroGear.Mobile.Auth.Credentials.CredentialManager.Store()'],['../interface_aero_gear_1_1_mobile_1_1_auth_1_1_credentials_1_1_i_credential_manager.html#ae049d03308f83e3fbd3ca61e12f51daf',1,'AeroGear.Mobile.Auth.Credentials.ICredentialManager.Store()']]],
  ['successful',['Successful',['../interface_aero_gear_1_1_mobile_1_1_core_1_1_http_1_1_i_http_response.html#a55886a0f95960ba3b9f3a1a27a04b953',1,'AeroGear::Mobile::Core::Http::IHttpResponse']]],
  ['systemexception',['SystemException',['../_i_logger_8cs.html#aecd6ef7b0182353f7b13b0327c2e6f95',1,'ILogger.cs']]],
  ['systemnethttprequest_2ecs',['SystemNetHttpRequest.cs',['../_system_net_http_request_8cs.html',1,'']]],
  ['systemnethttpresponse_2ecs',['SystemNetHttpResponse.cs',['../_system_net_http_response_8cs.html',1,'']]],
  ['systemnethttpservicemodule_2ecs',['SystemNetHttpServiceModule.cs',['../_system_net_http_service_module_8cs.html',1,'']]]
];
